[package]
authors = ["Philip Linden <lindenphilipj@gmail.com>"]
edition = "2021"
readme = "README.md"
name = "ahab_stm32f11ve"
version = "0.1.0"

[dependencies]
# cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = { workspace = true }
# cortex-m-semihosting = "0.5"
# panic-semihosting = "0.6.0"
# stm32f4xx-hal = { version = "0.22.1", features = ["stm32f411"] }

[[bin]]
name = "ahab_stm32f11ve"
test = false
bench = false
