[workspace]
resolver = "2"
members = ["crates/ahab"]

[workspace.package]
authors = ["Philip Linden <philiplinden@gmail.com>"]
edition = "2021"
license-file = "LICENSE-APACHE"
license = "MIT or Apache-2.0"
