name: Book

permissions:
  id-token: write
  contents: read
  pages: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36
    steps:
      - uses: actions/checkout@v4
      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install mdbook and plugins
        run: |
          cargo install mdbook-admonish --force
          cargo install mdbook-katex --force
          cargo install mdbook-mermaid --force
          cargo install mdbook-yml-header --force
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/book
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
